### ISSUE TITLE
how to change the color of the mask?

### ISSUE THREAD

**Issue by KevinWang676** [hustvl/EVF-SAM#10]
i wanna get the masked video in black and white like this 

![image](https://github.com/user-attachments/assets/85a03cf4-4b4f-48be-a6c8-20ef97839501)

so i wonder how to change the color of the mask and background. thanks a lot!

**Comment by CoderZhangYx** [comment]
modify https://github.com/hustvl/EVF-SAM/blob/main/inference_video.py#L176

I guess you simply want the segmentation map, so changing this line to
```out = output[i][1].transpose(1,2,0) * 255```
may work.

**Comment by KevinWang676** [comment]
thanks! it works, however, the length of the output (masked) video is less than the length of the input video. how can i fix it?

**Comment by KevinWang676** [comment]
i found that it is because the frames per second of the output (masked) video are 30, and my input video has 25 fps. thx!
