### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by luoshuiyue** [hustvl/EVF-SAM#12]
how to handle this:
![1724207937297](https://github.com/user-attachments/assets/0c4b179f-2a32-4ba0-a349-b6ad5e62b241)
![1724207949902](https://github.com/user-attachments/assets/03af6699-29e8-4e7b-91d2-5e3c8bdd1faf)

**Comment by CoderZhangYx** [comment]
the param passed to ***--version*** should be your local checkpoint direction or a huggingface format path.
If your server can connect to huggingface correctly, simply use ***--version YxZhang/evf-sam2*** and the code will automatically download checkpoint from huggingface. If not, manually download the checkpoint from https://huggingface.co/YxZhang/evf-sam2 and refer the exact direction to ***--version***
Sorry for the confusion from our documentation, we will make it clear soon.

**Comment by luoshuiyue** [comment]
Thanks, it works. I still encounter some different results between `inference.py` and `inference_video.py` which use the same model and the same input picture:
![微信图片_20240821142825](https://github.com/user-attachments/assets/0ca408ef-0a45-478a-9ded-e1938133ff72)

Why do the `inference_video.py` get worse results?

**Comment by CoderZhangYx** [comment]
We used to encounter similar phenomenon when we forgot to convert BGR to RGB during preprocess. Did you modify the code? If not, would you please provide us with the raw picture to help us figure out the reason? Thanks

**Comment by luoshuiyue** [comment]
I didn't modify the code, but I used the image dataset not the dataset coming from the video.Below is my first picture:
![000](https://github.com/user-attachments/assets/55c5b9e3-f0b0-423d-b099-eeaff16b90ad)

**Comment by CoderZhangYx** [comment]
what is your prompt?

**Comment by luoshuiyue** [comment]
the person in black standing on the brown disc base whose shoulders and head are blocked

**Comment by CoderZhangYx** [comment]
We observe the gap too. Temporarily we guess the problem lies in some unaligned inference setting between two predictor. We will dive deep into this problem and update this issue if we have any discovery. Thanks for reporting bug.

**Comment by luoshuiyue** [comment]
I find that the first few frames in the video inference results seems not good, but after that it become stable and good, so could it back propagation to optimize the results at the beginning.

**Comment by luoshuiyue** [comment]
Thanks for your detailed explanation.

**Comment by luoshuiyue** [comment]
@CoderZhangYx  Hi~ Why, based on the method of video transmission `inference_video.py,` there will be several interrupted frames in the middle, one with a bag mask and next one with no bag mask, two times in a row. (given prompt "person", if I give the prompt "person with bag", the results will be worse. WHAT I WANT is the person standing on the disc base is completely picked out, no matter how complicated his clothing and accessories are, and the clothing accessories are picked together.)
![image](https://github.com/user-attachments/assets/d2b7bd83-5c9f-4205-8a34-6a840addb0ea)

**Comment by CoderZhangYx** [comment]
Hi, thank you for using our model. 
Due to limited training data, our model maynot behave perfectly in all cases, especially in zero-shot video prediction. Our next release of checkpoint would include more training data, you may try then.

**Comment by CoderZhangYx** [comment]
Our latest release of code have solved the gap. Reopen this issue or open another issue if you have further problems.
