### ISSUE TITLE
what is <path to evf-sam> ?

### ISSUE THREAD

**Issue by benlyazid** [hustvl/EVF-SAM#13]
hi, Does anyone know What I should put in   --version <path to evf-sam> ?

**Comment by CoderZhangYx** [comment]
It is checkpoint path. Simply specify it to "YxZhang/evf-sam2" for huggingface auto-download api, or manually download the checkpoint to a local path and refer the path to "--version" .

**Comment by benlyazid** [comment]
Thank you
