### ISSUE TITLE
return segment objects coordinates 

### ISSUE THREAD

**Issue by benlyazid** [hustvl/EVF-SAM#14]
Hi,
Can I return segment coordinates from `python inference.py....` instead of image segmented, because I want to create a new image from just the segmented objects?
Thanks

**Comment by CoderZhangYx** [comment]
Do you mean polygon? or the binary segmentation mask?

**Comment by CoderZhangYx** [comment]
see #10

**Comment by benlyazid** [comment]
Yes like a plygon, the solution that I found until now is 
Iterate over pred_mask and get the minimum and maximum X, Y
`shape = pred_mask.shape

    width = shape[1]
    height = shape[0]
    max_x = 0
    max_y = 0
    min_x = width
    min_y = height
    for i in range(width):
        for j in range(height):
            if pred_mask[j][i] != False:
                max_x = max(max_x, i)
                max_y = max(max_y, j)
                min_x = min(min_x, i)
                min_y = min(min_y, j)
    print("max_x: ", max_x)
    print("max_y: ", max_y)
    print("min_x: ", min_x)
    print("min_y: ", min_y)
    image_crop = image_np[min_y:max_y, min_x:max_x]
    cv2.imwrite(save_path, image_crop)`

**Comment by CoderZhangYx** [comment]
if you want the polygon, try
```
cv2.findCountours(...)
```
if you want the bounding box, try
```
cv2.boundingRect(...)
```

**Comment by CoderZhangYx** [comment]
```pip install opencv-python``` before using these apis
