### ISSUE TITLE
tokenizer

### ISSUE THREAD

**Issue by rongfu-dsb** [hustvl/EVF-SAM#15]
嗨，很棒的工作！能告诉我在训练过程中，args.version应该设置成什么吗？
我尝试将其设置为xlm-roberta-base，但是不幸的是，xlm-roberta-tokenizer的vocab_size与beit-3的vocab_size好像并不相同，这导致我出现了词表越界的错误，不能训练模型。

**Comment by CoderZhangYx** [comment]
Hi, feel free to use English to ask questions. We will try our best to answer all the issues.
Glad to hear that you reproduce the training code. About the tokenizer, you can refer to the definition of [BEIT-3](https://github.com/microsoft/unilm/tree/master/beit3#text-tokenizer) readme.

**Comment by rongfu-dsb** [comment]
Thank you very much; you have solved a big problem for me.

**Comment by Shaosifan** [comment]
> 嗨，很棒的工作！能告诉我在训练过程中，args.version应该设置成什么吗？ 我尝试将其设置为xlm-roberta-base，但是不幸的是，xlm-roberta-tokenizer的vocab_size与beit-3的vocab_size好像并不相同，这导致我出现了词表越界的错误，不能训练模型。

请问您复现的时候args.version设置成什么了呢？
