### ISSUE TITLE
Ask for MAE Pretrained Encoder used for weight initialization before training

### ISSUE THREAD

**Issue by Le-Bao-181003** [hustvl/EVF-SAM#18]
I'm learning about the structure of the SAM model, and I'm wondering where you get the weights to initialize.
Thank you.

**Comment by CoderZhangYx** [comment]
[SAM](https://github.com/facebookresearch/segment-anything?tab=readme-ov-file#model-checkpoints) open-sourced their pretrained checkpoints. Please read their README.
