### ISSUE TITLE
完全无法识别出对象

### ISSUE THREAD

**Issue by pandayummy** [hustvl/EVF-SAM#19]
https://huggingface.co/spaces/wondervictor/evf-sam2
在这里测试，无论是hair 还是 face都是整个人物

![image](https://github.com/user-attachments/assets/e06fe914-9f99-411a-ab8a-c38c983d06fc)

![image](https://github.com/user-attachments/assets/51ca5b4c-293e-4922-b580-f14492eb4dfb)

测试图片：
![Person (1)](https://github.com/user-attachments/assets/250aff01-4fa2-4423-9d36-644bae55d0b8)

**Comment by CoderZhangYx** [comment]
We did not include a body part dataset in the training of our initial checkpoint release. The available open-source datasets for Referring Expression Segmentation (RefCOCO/+/g, RefCLEF) contain only about 80k images, limiting the model's zero-shot capabilities for tasks like part segmentation. Our previous experiments revealed challenges when directly adding part datasets during training. We will try to make use of the available part datasets (e.g. pascal_part, PartImageNet) in our future release.

**Comment by pandayummy** [comment]
https://huggingface.co/mattmdjaga/segformer_b2_clothes
https://huggingface.co/sayeed99/segformer-b3-fashion

把这两个针对人体部位的模型吸收了就好了。

**Comment by CoderZhangYx** [comment]
Nice advice! We will analyze if their released dataset can be used in our model! Thanks!

**Comment by CoderZhangYx** [comment]
Our latest release of checkpoint have supported semantic-level segmentation and part segmentation.
