### ISSUE TITLE
About the learnable params

### ISSUE THREAD

**Issue by cocoshe** [hustvl/EVF-SAM#20]
![image](https://github.com/user-attachments/assets/b347220b-9de0-4c7c-8ba6-4e51b611f7f7)

For EVF-SAM with SAM1, the learnable params are `Multimodel Encoder`, `Prompt Encoder`, `Mask Decoder`, and the `Projector`.

And I noticed the table in readme:

![image](https://github.com/user-attachments/assets/962a73ab-2671-47b7-b303-7464cb01eb8a)

For SAM2, you mean the learnable params are just the `Multimodel Encoder` and `Projector`? 
If so, why not train the other two parts, because of the computational cost?

**Comment by CoderZhangYx** [comment]
It is because we want to maintain the video prediction capability of SAM-2.

**Comment by cocoshe** [comment]
> It is because we want to maintain the video prediction capability of SAM-2.

Thanks for your quick reply, really great work~

**Comment by CoderZhangYx** [comment]
Thank you.
