### ISSUE TITLE
How do you train with a semantic segmentation dataset in ablation?

### ISSUE THREAD

**Issue by wysnzzzz** [hustvl/EVF-SAM#3]
Enter the category name as text?

**Comment by wysnzzzz** [comment]
And how long does it take to inference about an example?

**Comment by CoderZhangYx** [comment]
1. Yes, we simply follow [LISA](https://github.com/dvlab-research/LISA) to input the semantic category name as the text prompt. We've tried some template construction strategies like "all {object}" mentioned in some other papers, but still find the performance decrease on RES tasks.
2. It should take about 1.4s (including pre-process and post-process) on a T4 GPU per inference for our released scale of model (1.32b).

**Comment by wysnzzzz** [comment]
Thank you very much for your answer.
