### ISSUE TITLE
EffiSAM weight

### ISSUE THREAD

**Issue by shunliu01** [hustvl/EVF-SAM#33]
Hi authors,
Appreciate your amazing work!

Our question is, where is the EfficientSAM weight used in the original paper, do you have plan to open-source them?

Thanks!

**Comment by CoderZhangYx** [comment]
Due to company policy, we are only able to open-source few pretrained checkpoints. We're sorry.

**Comment by Shaosifan** [comment]
> Due to company policy, we are only able to open-source few pretrained checkpoints. We're sorry.

In the training phase, what kind of pretrained weights of EfficientSAM are used? Is the EfficientSAM-S?

**Comment by CoderZhangYx** [comment]
yes, we use EfficientSAM-S

**Comment by shunliu01** [comment]
Thanks for your reply!
I’m deploying your model for inference and find that both of SAM/SAM2 have relatively slow speeds, my hardware is 4* A6000, so wondering if there is any tricks for accelerating the model inference other then change the pretrained model into EffiSAM.

-Shun

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CoderZhangYx** [comment]
Thanks for deploying our model! You can enable fp16 or even int8 / int4 to accelerate inference. Furthermore, enabling flash-attention could be considered.
