### ISSUE TITLE
Is the tokenizer trained alongside with the EVF-SAM?

### ISSUE THREAD

**Issue by GinnyXiao** [hustvl/EVF-SAM#35]
Dear authors,

Thanks for your great work! I was wondering if you are using a tokenizer that has already been pre-trained on large text corpora, taken from BEiT-3, or are you training a tokenizer alongside with your EVF-SAM model? If the former, may I ask which tokenizer checkpoint you are using?

**Comment by CoderZhangYx** [comment]
There are no parameters in a tokenizer, so there is no way a tokenizer can be trained.
Just download the tokenizer claimed here https://github.com/microsoft/unilm/tree/master/beit3#text-tokenizer

**Comment by GinnyXiao** [comment]
Thanks you!
