### ISSUE TITLE
BeiT version

### ISSUE THREAD

**Issue by lzl2040** [hustvl/EVF-SAM#36]
The beit-large is the itc-version?

**Comment by CoderZhangYx** [comment]
no, we use the mlm-pretraining version.

**Comment by lzl2040** [comment]
> no, we use the mlm-pretraining version.

Is this weight?[link](https://github.com/addf400/files/releases/download/beit3/beit3_large_patch16_224.pth)

**Comment by CoderZhangYx** [comment]
yes
