### ISSUE TITLE
EVF-SAM2 Video demo!

### ISSUE THREAD

**Issue by wondervictor** [hustvl/EVF-SAM#5]
`prompt='boy'`

https://github.com/user-attachments/assets/13a8e1d4-466c-4210-bbc4-7b0985c405bd

`prompt='cat'`

https://github.com/user-attachments/assets/1e232cda-9acc-4e8e-a90d-39a6a57fa4b0

`prompt='dog'`

https://github.com/user-attachments/assets/40863df9-2292-4946-9de0-0c26d13ec29d

`prompt='left elephant'`

https://github.com/user-attachments/assets/5dccc4bf-6930-412e-b2f5-4523bfd4bb81

`prompt='person in black'`

https://github.com/user-attachments/assets/53195d52-b696-45cd-b61c-8cb7d39f0b16

**Comment by yqdch** [comment]
Cool, looking forward to updates
